### ISSUE TITLE
Upgrade to Gradle API 3.2.1

### ISSUE THREAD

**Issue by eriklupander** [echocat/gradle-golang-plugin#15]
First - thanks for a really nice plugin!

I recently upgraded Gradle from 3.1 to 3.2.1 (OS X Sierra, JDK 8u66).

Problem with plugin version 0.1.11 and 0.1.12.

Everything works fine with Gradle 3.1, with Gradle 3.2.1 running a simple "gradle build" fails on the :prepareToolChain task with the following stacktrace:

```
Caused by: java.lang.NoSuchMethodError: org.gradle.api.internal.tasks.TaskStateInternal.upToDate()V
        at org.echocat.gradle.plugins.golang.tasks.PrepareToolchain.run(PrepareToolchain.java:48)
        at org.echocat.gradle.plugins.golang.tasks.GolangTaskSupport.runBare(GolangTaskSupport.java:99)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:624)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:607)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
```

**Comment by blaubaer** [comment]
Hi @eriklupander!

Thank you for your report. I will reproduce this as fast as possible and try to fix it.

Cheers

**Comment by blaubaer** [comment]
New version (0.1.13) released that is not compatible to new API of Gradle 3.2.1

**Comment by eriklupander** [comment]
Thanks, works fine now.
